### ISSUE TITLE
SyntaxError in generator-angular-lazy\state\index.js

### ISSUE THREAD

**Issue by talvor** [matoilic/generator-angular-lazy#1]
Hi, when using the yeoman generator to generate the application or a new state I receive the following error.

```
const baseContext = super._createContext(...arguments);
                                                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.defineProperty.get [as angular-lazy:state] (C:\Users\phall\AppData\Roaming\nvm\v4.2.4\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\phall\AppData\Roaming\nvm\v4.2.4\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\phall\AppData\Roaming\nvm\v4.2.4\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:259:21)
```

Any idea what is causing this?

**Comment by UnnoTed** [comment]
the same happened to me, i had to use node 5 to make it work

**Comment by matoilic** [comment]
I oversaw there the spread operator in the last release. Fixed now.
