### ISSUE TITLE
E2E tests fail in newest version

### ISSUE THREAD

**Issue by BorntraegerMarc** [matoilic/generator-angular-lazy#10]
Hi guys

I noticed that the E2E tests fail on the newest version. Not sure if it's a problem with the generator or with the protractor version...
Here's the output:
[20:36:12] Using gulpfile Z:\Workspaces\example-project\gulpfile.js
[20:36:12] Starting 'copy-static'...
[20:36:12] Starting 'compile-source'...
[20:36:12] Starting 'compile-stylesheets'...
[20:36:12] Starting 'webdriver-update'...
[20:36:12] Finished 'compile-stylesheets' after 372 ms
[20:36:12] Finished 'copy-static' after 419 ms
[20:36:12] Finished 'compile-source' after 424 ms
[20:36:12] Starting 'build'...
[20:36:12] Finished 'build' after 6.52 μs
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.51/selenium-server-standalone-2.51.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip...
Updating IEDriver
downloading https://selenium-release.storage.googleapis.com/2.51/IEDriverServer_x64_2.51.0.zip...
IEDriverServer_2.51.0.zip downloaded to Z:\Workspaces\example-project\node_modules\gulp-protractor\node_modules\protractor\selenium\IEDriverServer_2.51.0.zip
chromedriver_2.21.zip downloaded to Z:\Workspaces\example-project\node_modules\gulp-protractor\node_modules\protractor\selenium\chromedriver_2.21.zip
selenium-server-standalone-2.51.0.jar downloaded to Z:\Workspaces\example-project\node_modules\gulp-protractor\node_modules\protractor\selenium\selenium-server-standalone-2.51.0.jar
[20:36:15] Finished 'webdriver-update' after 3.53 s
[20:36:15] Starting 'test-e2e'...
[20:36:15] Server started http://localhost:8089
ERROR - failed loading configuration file Z:\Workspaces\example-project\gulp-tasks/../config/protractor.js
Z:\Workspaces\example-project\config\protractor.js:3
let protractorBase = `${__dirname}/../node_modules/protractor/`;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at ConfigParser.addFileConfig (Z:\Workspaces\example-project\node_modules\gulp-protractor\node_modules\protractor\lib\configParser.js:195:22)
    at Object.init (Z:\Workspaces\example-project\node_modules\gulp-protractor\node_modules\protractor\lib\launcher.js:103:18)
    at Object.<anonymous> (Z:\Workspaces\example-project\node_modules\gulp-protractor\node_modules\protractor\lib\cli.js:140:23)

Z:\Workspaces\example-project\gulp-tasks\test-e2e.js:23
                throw err;
                ^
 Error: protractor exited with code 1

Cheerio!

**Comment by matoilic** [comment]
There was a missing strict mode annotation. This shouldn't be an issue with the latest 4.x and 5.x releases of Node.
