### ISSUE TITLE
module not found - on install

### ISSUE THREAD

**Issue by nicolaeracovita** [matoilic/generator-angular-lazy#14]
Hello,

running `yo angular-lazy` throws an exception:

```
Error: Cannot find module '../base'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/nracovit/.nvm/versions/node/v6.2.0/lib/node_modules/generator-angular-lazy/app/index.js:3:14)

```

I'm not sure how to fix it. I did install the generator, then run the command.

Thanks,

**Comment by matoilic** [comment]
For some reason `npm publish` ignored the `base.js` file, even though it was in the `files` array in `package.json`. Had to switch to including all files by default and exclude unwanted ones through `.npmingore`.
