### ISSUE TITLE
Transition aborted after upgrading angular to 1.6.1 and ui-router to 0.4.2

### ISSUE THREAD

**Issue by SamarRizvi** [matoilic/generator-angular-lazy#35]
I have a state named` 'app.profile'`. Here is it's route code

```
$stateProvider
        .state('app.profile', {
            url: 'profile',
            resolve: {
                profile: ['$state', 'authService', 'userDataService', '$q', ($state, authService, userDataService, $q) => {
                    let deferred = $q.defer();
                    authService.auth().$requireSignIn().then(function (auth) {
                        userDataService.getProfile(auth.uid).$loaded().then(function (profile) {
                            if (profile.joinedClasses) {
                                $state.go('app.dashboard.group.create', {classId: Object.keys(profile.joinedClasses)[0]});
                            } else if (profile.classId) {
                                $state.go('app.dashboard.group.create', {classId: profile.classId});
                            } else if (profile.userType && profile.userType === 'professor') {
                                $state.go('app.createClass');
                            } else if (profile.userType && profile.userType === 'student') {
                                $state.go('app.profileStudent');
                            } else {
                                deferred.resolve();
                            }
                        });
                    });
                    return deferred.promise;
                }]
            },
            views: {
                application: {
                    controller: 'ProfileStateController as profileState',
                    template
                }
            }
        })
```

And in routing.js, I have 
```
function routingConfig($locationProvider, $urlRouterProvider, $httpProvider, $futureStateProvider) {
    $httpProvider.useApplyAsync(true);
    futureStates.forEach((state) => $futureStateProvider.futureState(state));
    $locationProvider.html5Mode(false);
    $urlRouterProvider.otherwise('/profile');
    $urlRouterProvider.when('/', '/profile');
}
```
Now, when I directly open the url **http://localhost/#!/profile**, I get the following error once, and the _state transition to **'app.dashboard.group.create'** takes place:_

```
Error: transition aborted
    at $StateProvider.$get (http://localhost:8088/jspm_packages/github/angular-ui/ui-router@0.4.2/release/angular-ui-router.js:2971:64)
    at Object.invoke (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4845:19)
    at $StateProvider.origProvider.$get (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4712:43)
    at Object.invoke (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4845:19)
    at $StateProvider.origProvider.$get (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4712:43)
    at Object.invoke (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4845:19)
    at $StateProvider.origProvider.$get (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4712:43)
    at Object.invoke (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4845:19)
    at eval (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4639:37)
    at Object.getService [as get] (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.6.1/angular.js:4786:32) Possibly unhandled rejection: {}
```
And when I am on http://localhost, page is redirected to profile page, and the above error occurs multiple times for **'app.dashboard.group.create'** and gets stuck in digest loop and _no state transition to **'app.dashboard.group.create'** takes place_

The above error has started occuring after angular and ui-router upgrade.

**Comment by matoilic** [comment]
This is a known issue in ui-router / ui-router-extras and not an issue withing the generator.

https://github.com/christopherthielen/ui-router-extras/issues/356
